// src/pages/Login.tsx
import { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'react-router-dom';
import { LoginBox } from '@/components/LoginBox';
import { RegistryBox } from '@/components/RegistryBox';
import { Button } from '@/components/ui/button';
import { useAppStore } from '@/store';
import { useTranslations } from '@/contexts/useTranslations';
import globalContext from '@/context';

function LoginContent() {
  const { t } = useTranslations();
  const [searchParams] = useSearchParams();
  const [showLogin, setShowLogin] = useState(true);
  const { metaConfig, loadUserInfo } = useAppStore();

  const next = searchParams.get('next');

  useEffect(() => {
    loadUserInfo();
  }, [loadUserInfo]);

  const handleLoginRedirect = (code: string) => {
    if (next) {
      window.location.href = next.indexOf('?') !== -1 ? `${next}&code=${code}` : `${next}?code=${code}`;
      return;
    }
    window.location.href = globalContext.siteUrl || '/';
  };

  return (
    <div className="flex min-h-[calc(100vh-3.5rem)] flex-col items-center justify-center gap-4 p-4">
      {showLogin ? (
        <LoginBox onLoginRedirect={handleLoginRedirect} />
      ) : (
        <RegistryBox onLoginRedirect={handleLoginRedirect} />
      )}
      <div className="flex items-center gap-3 text-sm">
        {showLogin && !metaConfig.registry_locked && (
          <Button variant="link" size="sm" onClick={() => setShowLogin(false)} className="h-auto p-0 text-neutral-500">
            {t.goToRegistry}
          </Button>
        )}
        {!showLogin && (
          <Button variant="link" size="sm" onClick={() => setShowLogin(true)} className="h-auto p-0 text-neutral-500">
            {t.backToLogin}
          </Button>
        )}
        {showLogin && (
          <>
            {!metaConfig.registry_locked && <span className="text-neutral-300">|</span>}
            <Button variant="link" size="sm" asChild className="h-auto p-0 text-neutral-500">
              <a href="/reset-password">{t.goToReset}</a>
            </Button>
          </>
        )}
      </div>
    </div>
  );
}

export function Login() {
  return (
    <Suspense fallback={<div className="flex min-h-[calc(100vh-3.5rem)] items-center justify-center">Loading...</div>}>
      <LoginContent />
    </Suspense>
  );
}

// src/views/Login.vue
<template>
  <a-space
    id="login"
    align="center"
    direction="vertical"
  >
    <login-box
      v-show="showLogin"
      @login-redirect="loginRedirect"
    />
    <registry-box
      v-show="!showLogin"
      @login-redirect="loginRedirect"
    />
    <a-divider
      id="login-bottom-divider"
      orientation="center"
      :margin="40"
    >
      <div style="display: flex">
        <a-button
          v-if="showLogin && !registryLocked"
          type="text"
          @click="handleToggle"
        >
          {{ $t('goToRegistry') }}
        </a-button>
        <a-button
          v-if="!showLogin"
          type="text"
          @click="handleToggle"
        >
          {{ $t('backToLogin') }}
        </a-button>
        <a-button
          v-if="showLogin"
          type="text"
          @click="goToReset"
        >
          {{ $t('goToReset') }}
        </a-button>
      </div>
    </a-divider>
  </a-space>
</template>

<script setup>
import {useRoute, useRouter} from 'vue-router';
import {computed, ref} from 'vue';
import LoginBox from '@/components/LoginBox.vue';
import RegistryBox from '@/components/RegistryBox.vue';
import globalContext from '@/context';
import {useStore} from 'vuex';

// store
const store = useStore();
const registryLocked = computed(() => Boolean(store.state.metaConfig.registry_locked));

// route
const route = useRoute();
const router = useRouter();
const next = computed(() => route.query.next);

// login & registry
const showLogin = ref(true);
const handleToggle = () => (showLogin.value = !showLogin.value);

// redirect
const loginRedirect = (code) => {
  if (next.value) {
    window.location.href = next.value.indexOf('?') !== -1 ? `${next.value}&code=${code}` : `${next.value}?code=${code}`;
    return;
  }
  window.location.href = globalContext.siteUrl;
};

// reset
const goToReset = () => {
  router.push({name: 'ResetPassword'});
};
</script>

<style scoped>
#login {
  width: 100%;
  height: 100%;
  align-items: center;
  justify-content: center;
}

#login-bottom-divider {
  width: 360px;
}
</style>
