// src/components/LoginBox.tsx
import { useState, type FormEvent, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { User, Lock, MessageCircle, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { useAppStore } from '@/store';
import { useTranslations } from '@/contexts/useTranslations';
import { signInAPI, oauthCodeAPI, signOutAPI, getWeChatConfigAPI, weChatLoginAPI } from '@/api/user';
import { getTCaptchaConfigAPI, type TCaptchaConfig } from '@/api/tcaptcha';
import { hashPassword } from '@/lib/encrypt';
import { checkTCaptcha } from '@/lib/tcaptcha';
import globalContext from '@/context';

declare global {
  interface Window {
    WxLogin: new (options: {
      self_redirect: boolean;
      id: string;
      appid: string;
      scope: string;
      redirect_uri: string;
      state: string;
      style: string;
      href: string;
    }) => void;
  }
}

interface LoginBoxProps {
  onLoginRedirect: (code: string) => void;
}

export function LoginBox({ onLoginRedirect }: LoginBoxProps) {
  const { t } = useTranslations();
  const [loading, setLoading] = useState(false);
  const [weChatLoading, setWeChatLoading] = useState(false);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [readAgreement, setReadAgreement] = useState(false);
  const [error, setError] = useState('');
  const [useCurrent, setUseCurrent] = useState(false);
  const [useCustom, setUseCustom] = useState(false);
  const [useWeChat, setUseWeChat] = useState(false);
  const [weChatQuickLoginUrl, setWeChatQuickLoginUrl] = useState('');
  const [tcaptchaConfig, setTcaptchaConfig] = useState<TCaptchaConfig | null>(null);
  const [weChatConfigLoaded, setWeChatConfigLoaded] = useState(false);

  const { user, metaConfig, weChatCode, setWeChatCode, isLogin } = useAppStore();

  useEffect(() => {
    getTCaptchaConfigAPI()
      .then((config) => setTcaptchaConfig(config))
      .catch(() => setTcaptchaConfig({ is_enabled: false, app_id: '', aid_encrypted: '' }));
  }, []);

  const initWeChatLogin = useCallback(() => {
    const url = new URL(window.location.href);
    const next = url.searchParams.get('next') || '';
    const redirectURI = `${globalContext.siteUrl}/login/?next=${encodeURIComponent(next)}`;
    console.log(redirectURI)

    getWeChatConfigAPI()
      .then((res) => {
        setWeChatConfigLoaded(true);
        if (res && res.app_id) {
          if (res.is_wechat) {
            setWeChatQuickLoginUrl(
              'https://open.weixin.qq.com/connect/oauth2/authorize' +
                `?appid=${res.app_id}` +
                `&redirect_uri=${encodeURIComponent(redirectURI)}` +
                '&response_type=code' +
                '&scope=snsapi_userinfo' +
                `&state=${res.state}` +
                '#wechat_redirect'
            );
          } else {
            // eslint-disable-next-line no-new
            new window.WxLogin({
              self_redirect: false,
              id: 'wxlogin',
              appid: res.app_id,
              scope: 'snsapi_login',
              redirect_uri: encodeURIComponent(redirectURI),
              state: res.state || '',
              style: '',
              href: 'https://www.ovinc.cn/extra-assets/css/wechat_login.css?v=1718266759',
            });
          }
        }
      })
      .catch(() => {
        setWeChatConfigLoaded(true);
      });
  }, []);

  const checkWeChatLogin = useCallback(() => {
    const url = new URL(window.location.href);
    const code = url.searchParams.get('code');
    const state = url.searchParams.get('state');

    if (code && state) {
      setWeChatLoading(true);
      weChatLoginAPI({ code, state, is_oauth: true })
        .then((res) => {
          if ('code' in res && res.code) {
            onLoginRedirect(res.code);
          } else if ('wechat_code' in res && res.wechat_code) {
            setWeChatCode(res.wechat_code);
            setUseWeChat(false);
            setWeChatLoading(false);
          }
        })
        .catch((err) => {
          const errorMessage = (err as { message?: string })?.message || '';
          setError(errorMessage);
          setWeChatLoading(false);
        });
    }
  }, [onLoginRedirect, setWeChatCode]);

  useEffect(() => {
    checkWeChatLogin();
  }, [checkWeChatLogin]);

  useEffect(() => {
    if (useWeChat && !weChatConfigLoaded) {
      initWeChatLogin();
    }
  }, [useWeChat, weChatConfigLoaded, initWeChatLogin]);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!username || !password) {
      setError(t.UsernameRequired);
      return;
    }
    setLoading(true);
    setError('');

    try {
      const encryptedPassword = await hashPassword(password, username);

      if (tcaptchaConfig?.is_enabled) {
        checkTCaptcha(async (ret) => {
          if (ret.ret !== 0) {
            setError(ret.message || t.LoginFailed);
            setLoading(false);
            return;
          }
          await doSignIn(encryptedPassword, ret);
        });
      } else {
        await doSignIn(encryptedPassword, { ret: 0 });
      }
    } catch {
      setError(t.LoginFailed);
      setLoading(false);
    }
  };

  const doSignIn = async (encryptedPassword: string, tcaptchaResult: { ret: number; ticket?: string; randstr?: string }) => {
    try {
      const params = {
        username,
        password: encryptedPassword,
        is_oauth: true,
        tcaptcha: tcaptchaResult,
        ...(weChatCode && { wechat_code: weChatCode }),
      };
      if (weChatCode) {
        setWeChatCode('');
      }
      const res = await signInAPI(params);
      onLoginRedirect(res.code);
    } catch (err) {
      const errorMessage = (err as { message?: string })?.message || t.LoginFailed;
      setError(errorMessage);
      setLoading(false);
    }
  };

  const handleQuickLogin = async () => {
    setLoading(true);
    try {
      const res = await oauthCodeAPI();
      onLoginRedirect(res.code);
    } catch (err) {
      const errorMessage = (err as { message?: string })?.message || t.LoginFailed;
      setError(errorMessage);
      setLoading(false);
    }
  };

  const handleLogout = async () => {
    setLoading(true);
    try {
      await signOutAPI();
      window.location.reload();
    } catch (err) {
      const errorMessage = (err as { message?: string })?.message || '';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleSwitchAccount = () => {
    setUseCustom(true);
    setUseCurrent(false);
  };

  const handleWeChatQuickLogin = () => {
    window.location.href = weChatQuickLoginUrl;
  };

  if (isLogin && user.username && !useCustom && !useCurrent) {
    setUseCurrent(true);
  }

  if (useCurrent && user.username) {
    return (
      <Card className="w-full max-w-sm gap-0 border-neutral-200 py-0 shadow-sm dark:border-neutral-800">
        <CardHeader className="gap-0 border-b border-neutral-100 pb-4 pt-5 dark:border-neutral-800">
          <CardTitle className="text-center text-lg font-medium text-neutral-900 dark:text-neutral-100">
            <span dangerouslySetInnerHTML={{ __html: metaConfig.brand_name ? `${metaConfig.brand_name}&nbsp;` : '' }} />
            {t.LoginToOVINC}
          </CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4 p-5">
          <p className="mb-0 text-sm text-neutral-500 dark:text-neutral-400">{t.WelcomeBack}</p>
          <Button onClick={handleQuickLogin} disabled={loading} className="h-10 w-full">
            {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            <span dangerouslySetInnerHTML={{ __html: `${t.LoginAs}&nbsp;${user.nick_name}&nbsp;${t.LoginAsEnd}` }} />
          </Button>
          <div className="flex gap-3 text-sm">
            <Button variant="link" size="sm" onClick={handleSwitchAccount} disabled={loading} className="h-auto p-0 text-neutral-500">
              {t.loginAsAnother}
            </Button>
            <Button variant="link" size="sm" onClick={handleLogout} disabled={loading} className="h-auto p-0 text-orange-500">
              {t.logout}
            </Button>
          </div>
          {error && <p className="text-sm text-destructive">{error}</p>}
        </CardContent>
      </Card>
    );
  }

  if (useWeChat && !weChatCode) {
    return (
      <Card className="w-full max-w-sm gap-0 border-neutral-200 py-0 shadow-sm dark:border-neutral-800">
        <CardHeader className="gap-0 border-b border-neutral-100 pb-4 pt-5 dark:border-neutral-800">
          <CardTitle className="text-center text-lg font-medium text-neutral-900 dark:text-neutral-100">
            <span dangerouslySetInnerHTML={{ __html: metaConfig.brand_name ? `${metaConfig.brand_name}&nbsp;` : '' }} />
            {t.LoginToOVINC}
          </CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4 p-5">
          {weChatLoading ? (
            <div className="flex h-40 items-center justify-center">
              <Loader2 className="h-6 w-6 animate-spin text-green-600" />
            </div>
          ) : weChatQuickLoginUrl ? (
            <Button onClick={handleWeChatQuickLogin} className="h-10 w-full bg-green-600 hover:bg-green-700">
              <MessageCircle className="mr-2 h-4 w-4" />
              {t.WeChatQuickLogin}
            </Button>
          ) : (
            <div id="wxlogin" className="flex min-h-[180px] items-center justify-center" />
          )}

          <Separator />

          <Button variant="link" size="sm" onClick={() => setUseWeChat(false)} className="h-auto p-0 text-neutral-500">
            {t.UserPassLogin}
          </Button>

          {error && <p className="text-sm text-destructive">{error}</p>}
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="w-full max-w-sm gap-0 border-neutral-200 py-0 shadow-sm dark:border-neutral-800">
      <CardHeader className="gap-0 border-b border-neutral-100 pb-4 pt-5 dark:border-neutral-800">
        <CardTitle className="text-center text-lg font-medium text-neutral-900 dark:text-neutral-100">
          <span dangerouslySetInnerHTML={{ __html: metaConfig.brand_name ? `${metaConfig.brand_name}&nbsp;` : '' }} />
          {t.LoginToOVINC}
        </CardTitle>
      </CardHeader>
      <CardContent className="p-5">
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="username" className="text-sm text-neutral-600 dark:text-neutral-400">
              {t.Username}
            </Label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
              <Input
                id="username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                disabled={loading || weChatLoading}
                className="h-10 pl-9"
                placeholder={t.Username}
              />
            </div>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="password" className="text-sm text-neutral-600 dark:text-neutral-400">
              {t.Password}
            </Label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={loading || weChatLoading}
                className="h-10 pl-9"
                placeholder={t.Password}
              />
            </div>
          </div>
          {error && <p className="text-sm text-destructive">{error}</p>}
          <div className="flex gap-2 pt-1">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                setUsername('');
                setPassword('');
              }}
              disabled={loading || weChatLoading}
              className="h-10"
            >
              {t.Clear}
            </Button>
            <Button type="submit" disabled={loading || weChatLoading || !readAgreement} className="h-10 flex-1">
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              {weChatCode ? t.Bind : t.Submit}
            </Button>
          </div>
        </form>

        <div className="mt-4 flex items-start gap-2">
          <Checkbox
            id="agreement"
            checked={readAgreement}
            onCheckedChange={(checked) => setReadAgreement(checked as boolean)}
            className="mt-0.5"
          />
          <label htmlFor="agreement" className="text-xs leading-relaxed text-neutral-500 dark:text-neutral-400">
            {t.alreadyReadAgreement}
            <Link to="/agreement/user" className="text-blue-600 hover:underline dark:text-blue-400">
              {t.UserAgreement}
            </Link>
            {' & '}
            <Link to="/agreement/privacy" className="text-blue-600 hover:underline dark:text-blue-400">
              {t.PrivacyAgreement}
            </Link>
          </label>
        </div>

        <div className="mt-4 flex flex-col items-center gap-3">
          <Separator />
          <Button
            type="button"
            variant="link"
            size="sm"
            onClick={() => setUseWeChat(true)}
            disabled={loading || weChatLoading}
            className="h-auto p-0 text-green-600 hover:text-green-700"
          >
            <MessageCircle className="mr-1.5 h-4 w-4" />
            {t.WeChatQuickLogin}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

// src/components/LoginBox.vue
<template>
  <a-space
    id="login-box"
    direction="vertical"
  >
    <div id="login-box-title-box">
      <h2 id="login-box-title">
        {{ (metaConfig.brand_name ? `${metaConfig.brand_name} `: '') + $t('LoginToOVINC') }}
      </h2>
    </div>
    <a-form
      class="login-box-form"
      ref="formRef"
      :model="loginForm"
      @submit="handleSubmit"
      auto-label-width
      v-if="!useCurrent && !useWeChat"
    >
      <a-form-item
        field="username"
        :label="$t('Username')"
        :rules="loginFormRules.username"
        feedback
      >
        <a-input
          v-model="loginForm.username"
          :disabled="loading || weChatLoading"
          allow-clear
        >
          <template #prefix>
            <icon-user />
          </template>
        </a-input>
      </a-form-item>
      <a-form-item
        field="password"
        :label="$t('Password')"
        :rules="loginFormRules.password"
        feedback
      >
        <a-input-password
          v-model="loginForm.password"
          :disabled="loading || weChatLoading"
          allow-clear
        >
          <template #prefix>
            <icon-lock />
          </template>
        </a-input-password>
      </a-form-item>
      <a-form-item>
        <a-space>
          <a-button
            @click="$refs.formRef.resetFields()"
            :loading="loading || weChatLoading"
          >
            {{ $t('Clear') }}
          </a-button>
          <a-button
            html-type="submit"
            type="primary"
            :loading="loading || weChatLoading"
            :disabled="!readAgreement"
          >
            {{ wechatCode ? $t('Bind') : $t('Submit') }}
          </a-button>
        </a-space>
      </a-form-item>
      <a-form-item
        id="login-box-third-login"
        style="margin-top: 20px"
        v-if="false"
      >
        <a-button
          shape="circle"
          @click="initWeChatLogin()"
        >
          <icon-wechat style="color: #70b838" />
        </a-button>
      </a-form-item>
    </a-form>
    <a-space
      class="agreement-agree-box"
      v-if="!useCurrent && !useWeChat"
    >
      <a-checkbox v-model="readAgreement" />
      <div>
        {{ $t('alreadyReadAgreement') }}
        <a
          type="text"
          @click="router.push({name: 'Agreement', params: {type: 'user'}})"
        >
          {{ $t('UserAgreement') }}
        </a>
        &
        <a
          type="text"
          @click="router.push({name: 'Agreement', params: {type: 'privacy'}})"
        >
          {{ $t('PrivacyAgreement') }}
        </a>
      </div>
    </a-space>
    <a-spin
      v-if="useWeChat && !useCurrent && !weChatQuickLoginUrl"
      :loading="loading"
      style="width: 100%;"
    >
      <a-space
        id="wxlogin"
        v-if="useWeChat && !useCurrent && !weChatQuickLoginUrl"
      />
    </a-spin>
    <a-space
      style="width: 100%; align-items: center; justify-content: center; margin: 20px 0"
      v-if="useWeChat && !useCurrent && weChatQuickLoginUrl"
    >
      <a-button
        type="primary"
        @click="weChatQuickLogin"
        status="success"
      >
        <icon-wechat style="margin-right: 8px" />{{ $t('WeChatQuickLogin') }}
      </a-button>
    </a-space>
    <div
      style="width: 100%; text-align: center; margin-bottom: 20px"
      v-if="useWeChat && !useCurrent"
    >
      <a-button
        type="text"
        @click="useWeChat = false"
        style="color: unset; text-decoration: underline;"
      >
        {{ $t('UserPassLogin') }}
      </a-button>
    </div>
    <a-space
      v-if="useCurrent"
      direction="vertical"
      class="login-box-form"
      style="align-items: center; justify-content: center; padding-top: 0"
      :size="[0, 0]"
    >
      <a-button
        type="primary"
        @click="quickLogin"
        :loading="loading || weChatLoading"
      >
        {{ $t('LoginAs') }}&nbsp;{{ user.nick_name }}&nbsp;{{ $t('LoginAsEnd') }}
      </a-button>
      <a-button
        type="text"
        @click="
          useCurrent = !useCurrent;
          initWeChatLogin();
        "
        :loading="loading || weChatLoading"
        style="margin-top: 10px"
      >
        {{ $t('loginAsAnother') }}
      </a-button>
    </a-space>
  </a-space>
</template>

<script setup>
import {computed, onMounted, ref} from 'vue';
import {useI18n} from 'vue-i18n';
import {getUserInfoAPI, getWeChatConfigAPI, oauthCodeAPI, signInAPI, weChatLoginAPI} from '@/api/user';
import {Message, Modal} from '@arco-design/web-vue';
import {handleLoading} from '@/utils/loading';
import {useStore} from 'vuex';
import globalContext from '@/context';
import {hashPassword} from '@/utils/encrypt';
import {checkTCaptcha} from '@/utils/tcaptcha';
import {useRouter} from 'vue-router';

const router = useRouter();

// loading
const loading = ref(false);
const weChatLoading = ref(false);

// emit
const emits = defineEmits(['loginRedirect']);

// locale
const i18n = useI18n();

// form
const loginForm = ref({
  username: '',
  password: '',
  is_oauth: true,
});
const loginFormRules = ref({
  username: [{required: true, message: i18n.t('UsernameRequired')}],
  password: [{required: true, message: i18n.t('PasswordRequired')}],
});
const readAgreement = ref(false);

// login
const handleSubmit = async ({values, errors}) => {
  if (errors) return;
  handleLoading(loading, true);
  const encryptedPassword = await hashPassword(values.password, values.username);
  const params = {...values, password: encryptedPassword};
  if (store.state.weChatCode) {
    params.wechat_code = store.state.weChatCode;
    store.commit('setWeChatCode', '');
  }
  checkTCaptcha((ret) => {
    params.tcaptcha = ret;
    signInAPI(params)
        .then(
            (res) => {
              Message.info(i18n.t('LoginSuccess'));
              emits('loginRedirect', res.data.code);
            },
            (err) => {
              Modal.warning({
                title: i18n.t('LoginFailed'),
                content: err.response.data.message,
                modalStyle: {textAlign: 'center'},
                width: 340,
                okText: i18n.t('OK'),
              });
              handleLoading(loading, false);
            },
        );
  });
};

// check Login
const store = useStore();
const user = computed(() => store.state.user);
const metaConfig = computed(() => store.state.metaConfig);
const useCurrent = ref(false);
onMounted(() => {
  handleLoading(loading, true);
  initWeChatLogin();
  getUserInfoAPI()
      .then((res) => {
        store.commit('setUser', res.data);
        store.commit('setIsLogin', true);
      })
      .finally(() => {
        const url = new URL(window.location.href);
        if (url.searchParams.has('code') && url.searchParams.has('state')) {
          checkWeChatLogin();
        } else {
          if (user.value.username) {
            useCurrent.value = true;
          }
          handleLoading(loading, false);
        }
      });
});
const quickLogin = () => {
  handleLoading(loading, true);
  oauthCodeAPI()
      .then(
          (res) => {
            Message.info(i18n.t('LoginSuccess'));
            emits('loginRedirect', res.data.code);
          },
          (err) => {
            Modal.warning({
              title: i18n.t('LoginFailed'),
              content: err.response.data.message,
              modalStyle: {textAlign: 'center'},
              width: 340,
              okText: i18n.t('OK'),
            });
            handleLoading(loading, false);
          },
      );
};

// WeChat
const wechatCode = computed(() => store.state.weChatCode);
const useWeChat = ref(true);
const weChatQuickLoginUrl = ref('');
const weChatQuickLogin = () => window.location.href = weChatQuickLoginUrl.value;
const initWeChatLogin = () => {
  useWeChat.value = true;
  const url = new URL(window.location.href);
  const next = url.searchParams.get('next');
  const redirectURI = `${globalContext.siteUrl}/login/?next=${encodeURIComponent(next)}`;
  getWeChatConfigAPI().then((res) => {
    if (res.data && res.data.app_id) {
      if (res.data.is_wechat) {
        weChatQuickLoginUrl.value =
          'https://open.weixin.qq.com/connect/oauth2/authorize' +
          `?appid=${res.data.app_id}` +
          `&redirect_uri=${encodeURIComponent(redirectURI)}` +
          '&response_type=code' +
          '&scope=snsapi_userinfo' +
          `&state=${res.data.state}` +
          '#wechat_redirect';
      } else {
        // eslint-disable-next-line no-undef
        new WxLogin({
          self_redirect: false,
          id: 'wxlogin',
          appid: res.data.app_id,
          scope: 'snsapi_login',
          redirect_uri: encodeURIComponent(redirectURI),
          state: res.data.state,
          style: '',
          href: 'https://www.ovinc.cn/extra-assets/css/wechat_login.css?v=1718266759',
        });
      }
    } else {
      useWeChat.value = false;
    }
  });
};
const checkWeChatLogin = () => {
  const url = new URL(window.location.href);
  const params = {
    code: url.searchParams.get('code'),
    state: url.searchParams.get('state'),
    is_oauth: true,
  };
  weChatLoginAPI(params).then(
      (res) => {
        if ('code' in res.data) {
          emits('loginRedirect', res.data.code);
        } else if ('wechat_code' in res.data) {
          store.commit('setWeChatCode', res.data.wechat_code);
          useWeChat.value = false;
          handleLoading(loading, false);
        }
      },
      (err) => {
        Message.error(err.response.data.message);
        handleLoading(loading, false);
      },
  );
};
</script>

<style scoped>
#login-box {
  border-radius: var(--border-radius-medium);
  border: 1px solid var(--color-border-1);
  box-sizing: border-box;
  box-shadow: var(--shadow2-center);
  width: 360px;
  overflow: hidden;
}

#login-box-title-box {
  background: linear-gradient(-45deg, rgb(var(--arcoblue-4)), rgb(var(--green-2)));
  padding: 32px 20px;
  margin-bottom: 20px;
}

#login-box-title {
  text-align: center;
  margin: 0;
  color: var(--color-white);
}

.login-box-form {
  width: 360px;
  padding: 20px;
  box-sizing: border-box;
}

#wxlogin {
  display: flex;
  align-items: center;
  justify-content: center;
}

#wxlogin :deep(iframe) {
  height: 260px;
}

.agreement-agree-box {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: -20px 0 20px 0;
  width: 100%;
  max-width: 360px;
  padding: 0 20px;
  box-sizing: border-box;
  word-break: break-all;
}

.agreement-agree-box :deep(.arco-space-item) > div > a {
  margin: 0;
  padding: 0;
  color: rgb(var(--arcoblue-6));
  cursor: pointer;
}
</style>
