// src/components/RegistryBox.tsx
import { useState, useEffect, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { User, Lock, Phone, Shield, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useAppStore } from '@/store';
import { useTranslations } from '@/contexts/useTranslations';
import { signUpAPI, sendVerifyCodeAPI, getPhoneAreasAPI } from '@/api/user';
import { getTCaptchaConfigAPI, type TCaptchaConfig } from '@/api/tcaptcha';
import { hashPassword } from '@/lib/encrypt';
import { checkTCaptcha } from '@/lib/tcaptcha';

interface RegistryBoxProps {
  onLoginRedirect: (code: string) => void;
}

export function RegistryBox({ onLoginRedirect }: RegistryBoxProps) {
    const { t } = useTranslations();
    const [loading, setLoading] = useState(false);
    const [sendingCode, setSendingCode] = useState(false);
    const [username, setUsername] = useState('');
    const [nickName, setNickName] = useState('');
    const [password, setPassword] = useState('');
    const [password2, setPassword2] = useState('');
    const [phoneArea, setPhoneArea] = useState('');
    const [phoneNumber, setPhoneNumber] = useState('');
    const [phoneVerify, setPhoneVerify] = useState('');
    const [readAgreement, setReadAgreement] = useState(false);
    const [error, setError] = useState('');
    const [waitTime, setWaitTime] = useState(0);
    const [phoneAreaOptions, setPhoneAreaOptions] = useState<{ value: string; label: string }[]>([]);
    const [tcaptchaConfig, setTcaptchaConfig] = useState<TCaptchaConfig | null>(null);

    const { passkeyCode, setPasskeyCode, weChatCode, setWeChatCode, metaConfig } = useAppStore();

    useEffect(() => {
        getPhoneAreasAPI().then((res) => {
            setPhoneAreaOptions(res);
        });
        getTCaptchaConfigAPI()
            .then((config) => setTcaptchaConfig(config))
            .catch(() => setTcaptchaConfig({ is_enabled: false, app_id: '', aid_encrypted: '' }));
    }, []);

    useEffect(() => {
        if (waitTime > 0) {
            const timer = setTimeout(() => setWaitTime(waitTime - 1), 1000);
            return () => clearTimeout(timer);
        }
    }, [waitTime]);

    const handleSendVerifyCode = () => {
        if (!phoneNumber) {
            setError(t.PhoneNumberRequired);
            return;
        }
        setError('');
        setSendingCode(true);

        if (tcaptchaConfig?.is_enabled) {
            checkTCaptcha(async (ret) => {
                if (ret.ret !== 0) {
                    setError(ret.message || '');
                    setSendingCode(false);
                    return;
                }
                try {
                    await sendVerifyCodeAPI({ phone_area: phoneArea, phone_number: phoneNumber, tcaptcha: ret });
                    setWaitTime(60);
                } catch (err) {
                    const errorMessage = (err as { message?: string })?.message || '';
                    setError(errorMessage);
                } finally {
                    setSendingCode(false);
                }
            });
        } else {
            sendVerifyCodeAPI({ phone_area: phoneArea, phone_number: phoneNumber })
                .then(() => setWaitTime(60))
                .catch((err) => {
                    const errorMessage = (err as { message?: string })?.message || '';
                    setError(errorMessage);
                })
                .finally(() => setSendingCode(false));
        }
    };

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        if (password !== password2) {
            setError(t.Password2NotMatch);
            return;
        }
        setLoading(true);
        setError('');

        try {
            const encryptedPassword = await hashPassword(password, username);

            if (tcaptchaConfig?.is_enabled) {
                checkTCaptcha(async (ret) => {
                    if (ret.ret !== 0) {
                        setError(ret.message || t.RegistryFailed);
                        setLoading(false);
                        return;
                    }
                    await doSignUp(encryptedPassword, ret);
                });
            } else {
                await doSignUp(encryptedPassword, { ret: 0 });
            }
        } catch {
            setError(t.RegistryFailed);
            setLoading(false);
        }
    };

    const doSignUp = async (encryptedPassword: string, tcaptchaResult: { ret: number; ticket?: string; randstr?: string }) => {
        try {
            const params = {
                username,
                nick_name: nickName,
                password: encryptedPassword,
                password2: encryptedPassword,
                phone_area: phoneArea,
                phone_number: phoneNumber,
                phone_verify: phoneVerify,
                is_oauth: true,
                tcaptcha: tcaptchaResult,
                ...(passkeyCode && { passkey_code: passkeyCode }),
                ...(weChatCode && { wechat_code: weChatCode }),
            };
            if (weChatCode) {
                setWeChatCode('');
            }
            const res = await signUpAPI(params);
            if (passkeyCode) {
                setPasskeyCode('');
            }
            onLoginRedirect(res.code);
        } catch (err) {
            const errorMessage = (err as { message?: string })?.message || t.RegistryFailed;
            setError(errorMessage);
            setLoading(false);
        }
    };

    return (
        <Card className="w-full max-w-sm gap-0 border-neutral-200 py-0 shadow-sm dark:border-neutral-800">
            <CardHeader className="gap-0 border-b border-neutral-100 pb-4 pt-5 dark:border-neutral-800">
                <CardTitle className="text-center text-lg font-medium text-neutral-900 dark:text-neutral-100">
                    <span dangerouslySetInnerHTML={{ __html: metaConfig.brand_name ? `${metaConfig.brand_name}&nbsp;` : '' }} />
                    {t.LoginToOVINC}
                </CardTitle>
            </CardHeader>
            <CardContent className="p-5">
                <form onSubmit={handleSubmit} className="space-y-3">
                    <div className="space-y-1.5">
                        <Label htmlFor="reg-username" className="text-sm text-neutral-600 dark:text-neutral-400">
                            {t.Username}
                        </Label>
                        <div className="relative">
                            <User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
                            <Input
                                id="reg-username"
                                value={username}
                                onChange={(e) => setUsername(e.target.value)}
                                disabled={loading}
                                className="h-10 pl-9"
                                placeholder={t.Username}
                            />
                        </div>
                    </div>
                    <div className="space-y-1.5">
                        <Label htmlFor="reg-nickname" className="text-sm text-neutral-600 dark:text-neutral-400">
                            {t.NickName}
                        </Label>
                        <div className="relative">
                            <User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
                            <Input
                                id="reg-nickname"
                                value={nickName}
                                onChange={(e) => setNickName(e.target.value)}
                                disabled={loading}
                                className="h-10 pl-9"
                                placeholder={t.NickName}
                            />
                        </div>
                    </div>
                    <div className="space-y-1.5">
                        <Label htmlFor="reg-password" className="text-sm text-neutral-600 dark:text-neutral-400">
                            {t.Password}
                        </Label>
                        <div className="relative">
                            <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
                            <Input
                                id="reg-password"
                                type="password"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                disabled={loading}
                                className="h-10 pl-9"
                                placeholder={t.Password}
                            />
                        </div>
                    </div>
                    <div className="space-y-1.5">
                        <Label htmlFor="reg-password2" className="text-sm text-neutral-600 dark:text-neutral-400">
                            {t.repeatPassword}
                        </Label>
                        <div className="relative">
                            <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
                            <Input
                                id="reg-password2"
                                type="password"
                                value={password2}
                                onChange={(e) => setPassword2(e.target.value)}
                                disabled={loading}
                                className="h-10 pl-9"
                                placeholder={t.repeatPassword}
                            />
                        </div>
                    </div>
                    <div className="space-y-1.5">
                        <Label className="text-sm text-neutral-600 dark:text-neutral-400">{t.PhoneArea}</Label>
                        <Select value={phoneArea} onValueChange={setPhoneArea} disabled={loading}>
                            <SelectTrigger className="h-10">
                                <SelectValue placeholder={t.PhoneArea} />
                            </SelectTrigger>
                            <SelectContent>
                                {phoneAreaOptions.map((option) => (
                                    <SelectItem key={option.value} value={option.value}>
                                        {option.label}
                                    </SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </div>
                    <div className="space-y-1.5">
                        <Label htmlFor="reg-phone" className="text-sm text-neutral-600 dark:text-neutral-400">
                            {t.PhoneNumber}
                        </Label>
                        <div className="relative">
                            <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
                            <Input
                                id="reg-phone"
                                value={phoneNumber}
                                onChange={(e) => setPhoneNumber(e.target.value)}
                                disabled={loading}
                                className="h-10 pl-9"
                                placeholder={t.PhoneNumber}
                            />
                        </div>
                    </div>
                    <div className="space-y-1.5">
                        <Label htmlFor="reg-verify" className="text-sm text-neutral-600 dark:text-neutral-400">
                            {t.PhoneVerifyCode}
                        </Label>
                        <div className="flex gap-2">
                            <div className="relative flex-1">
                                <Shield className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
                                <Input
                                    id="reg-verify"
                                    value={phoneVerify}
                                    onChange={(e) => setPhoneVerify(e.target.value)}
                                    disabled={loading || !phoneNumber}
                                    className="h-10 pl-9"
                                    placeholder={t.PhoneVerifyCode}
                                />
                            </div>
                            <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={handleSendVerifyCode}
                                disabled={!phoneNumber || waitTime > 0 || sendingCode}
                                className="h-10 whitespace-nowrap cursor-pointer"
                            >
                                {sendingCode && <Loader2 className="mr-1 h-3 w-3 animate-spin" />}
                                {waitTime > 0 ? `${waitTime}s` : t.SendVerifyCode}
                            </Button>
                        </div>
                    </div>
                    {error && <p className="text-sm text-destructive">{error}</p>}
                    <div className="flex gap-2 pt-1">
                        <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => {
                                setUsername('');
                                setNickName('');
                                setPassword('');
                                setPassword2('');
                                setPhoneNumber('');
                                setPhoneVerify('');
                            }}
                            disabled={loading}
                            className="h-10 cursor-pointer"
                        >
                            {t.Clear}
                        </Button>
                        <Button type="submit" disabled={loading || !readAgreement} className="h-10 flex-1 cursor-pointer">
                            {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                            {weChatCode || passkeyCode ? t.Bind : t.Submit}
                        </Button>
                    </div>
                </form>
                <div className="mt-4 flex items-start gap-2">
                    <Checkbox
                        id="reg-agreement"
                        checked={readAgreement}
                        onCheckedChange={(checked) => setReadAgreement(checked as boolean)}
                        className="mt-0.5"
                    />
                    <label htmlFor="reg-agreement" className="text-xs leading-relaxed text-neutral-500 dark:text-neutral-400">
                        {t.alreadyReadAgreement}
                        <Link to="/agreement/user" className="text-blue-600 hover:underline dark:text-blue-400">
                            {t.UserAgreement}
                        </Link>
                        {' & '}
                        <Link to="/agreement/privacy" className="text-blue-600 hover:underline dark:text-blue-400">
                            {t.PrivacyAgreement}
                        </Link>
                    </label>
                </div>
            </CardContent>
        </Card>
    );
}

// src/components/RegistryBox.vue
<template>
  <a-space
    id="registry-box"
    direction="vertical"
  >
    <div id="registry-box-title-box">
      <h2 id="registry-box-title">
        {{ $t('LoginToOVINC') }}
      </h2>
    </div>
    <a-form
      class="registry-box-form"
      ref="registryFormRef"
      :model="registryData"
      @submit="handleSubmit"
      auto-label-width
    >
      <a-form-item
        field="username"
        :label="$t('Username')"
        :rules="registryRules.username"
        feedback
      >
        <a-input
          v-model="registryData.username"
          :disabled="loading"
          :placeholder="$t('Username')"
          allow-clear
        >
          <template #prefix>
            <icon-user />
          </template>
        </a-input>
      </a-form-item>
      <a-form-item
        field="nick_name"
        :label="$t('NickName')"
        :rules="registryRules.nick_name"
        feedback
      >
        <a-input
          v-model="registryData.nick_name"
          :disabled="loading"
          :placeholder="$t('NickName')"
          allow-clear
        >
          <template #prefix>
            <icon-user />
          </template>
        </a-input>
      </a-form-item>
      <a-form-item
        field="password"
        :label="$t('Password')"
        :rules="registryRules.password"
        feedback
      >
        <a-input-password
          v-model="registryData.password"
          :disabled="loading"
          :placeholder="$t('Password')"
          allow-clear
        >
          <template #prefix>
            <icon-lock />
          </template>
        </a-input-password>
      </a-form-item>
      <a-form-item
        field="password2"
        :label="$t('Password')"
        :rules="registryRules.password2"
        feedback
      >
        <a-input-password
          v-model="registryData.password2"
          :disabled="loading"
          :placeholder="$t('repeatPassword')"
          allow-clear
        >
          <template #prefix>
            <icon-lock />
          </template>
        </a-input-password>
      </a-form-item>
      <a-form-item
        field="phone_area"
        :label="$t('PhoneArea')"
        :rules="registryRules.phoneArea"
        feedback
      >
        <a-select
          v-model="registryData.phone_area"
          :options="phoneAreaOptions"
          :disabled="loading"
          :placeholder="$t('PhoneArea')"
          :allow-search="true"
        >
          <template #prefix>
            <icon-phone />
          </template>
        </a-select>
      </a-form-item>
      <a-form-item
        field="phone_number"
        :label="$t('PhoneNumber')"
        :rules="registryRules.phoneNumber"
        feedback
      >
        <a-input
          v-model="registryData.phone_number"
          :disabled="loading"
          :placeholder="$t('PhoneNumber')"
          allow-clear
        >
          <template #prefix>
            <icon-phone />
          </template>
        </a-input>
      </a-form-item>
      <a-form-item
        field="phone_verify"
        :label="$t('PhoneVerifyCode')"
        :rules="registryRules.phoneVerify"
        feedback
      >
        <a-input
          v-model="registryData.phone_verify"
          :disabled="loading || registryData.phone_number.length <= 0"
          :placeholder="$t('PhoneVerifyCode')"
          allow-clear
        >
          <template #prefix>
            <icon-safe />
          </template>
        </a-input>
        <a-button
          type="primary"
          :disabled="registryData.phone_number.length <= 0 || waitTime > 0"
          @click="sendVerifyCode"
        >
          {{ waitTime > 0 ? `${waitTime}s` : i18n.t('SendVerifyCode') }}
        </a-button>
      </a-form-item>
      <a-form-item>
        <a-space>
          <a-button
            @click="$refs.registryFormRef.resetFields()"
            :loading="loading"
          >
            {{ $t('Clear') }}
          </a-button>
          <a-button
            html-type="submit"
            type="primary"
            :loading="loading"
            :disabled="!readAgreement"
          >
            {{ wechatCode ? $t('Bind') : $t('Submit') }}
          </a-button>
        </a-space>
      </a-form-item>
    </a-form>
    <a-space
      class="agreement-agree-box"
    >
      <a-checkbox v-model="readAgreement" />
      <div>
        {{ $t('alreadyReadAgreement') }}
        <a
          type="text"
          @click="router.push({name: 'Agreement', params: {type: 'user'}})"
        >
          {{ $t('UserAgreement') }}
        </a>
        &
        <a
          type="text"
          @click="router.push({name: 'Agreement', params: {type: 'privacy'}})"
        >
          {{ $t('PrivacyAgreement') }}
        </a>
      </div>
    </a-space>
  </a-space>
</template>

<script setup>
import {computed, onMounted, ref} from 'vue';
import {useI18n} from 'vue-i18n';
import {handleLoading} from '@/utils/loading';
import {signUpAPI, sendVerifyCodeAPI, getPhoneAreasAPI} from '@/api/user';
import {Message, Modal} from '@arco-design/web-vue';
import {useStore} from 'vuex';
import {hashPassword} from '@/utils/encrypt';
import {checkTCaptcha} from '@/utils/tcaptcha';
import {useRouter} from 'vue-router';

// route
const router = useRouter();

// loading
const loading = ref(false);

// emit
const emits = defineEmits(['loginRedirect']);

// store
const store = useStore();
const wechatCode = computed(() => store.state.weChatCode);

// i18n
const i18n = useI18n();

// config
const phoneAreaOptions = ref([]);
onMounted(() => {
  getPhoneAreasAPI().then((res) => (phoneAreaOptions.value = res.data));
});

// form
const readAgreement = ref(false);
const registryData = ref({
  username: '',
  nick_name: '',
  password: '',
  password2: '',
  phone_area: '',
  phone_number: '',
  phone_verify: '',
  is_oauth: true,
});
const password2Validator = (value, cb) => {
  if (registryData.value.password === registryData.value.password2) return;
  return cb(i18n.t('Password2NotMatch'));
};
const registryRules = ref({
  username: [
    {required: true, message: i18n.t('UsernameRequired')},
    {match: /^[a-zA-Z]{1}[a-zA-Z0-9]{5,}$/, message: i18n.t('UsernameRegexInvalid')},
  ],
  nick_name: [{required: true, message: i18n.t('NickNameRequired')}],
  password: [{required: true, message: i18n.t('PasswordRequired')}],
  password2: [{required: true, message: i18n.t('PasswordRequired')}, {validator: password2Validator}],
  phoneArea: [{required: true, message: i18n.t('PhoneAreaRequired')}],
  phoneNumber: [{required: true, message: i18n.t('PhoneNumberRequired')}],
  phoneVerify: [{required: true, message: i18n.t('PhoneVerifyRequired')}],
});

// registry
const handleSubmit = async ({values, errors}) => {
  if (errors) return;
  handleLoading(loading, true);
  const encryptedPassword = await hashPassword(values.password, values.username);
  const params = {...values, password: encryptedPassword, password2: encryptedPassword};
  if (store.state.weChatCode) {
    params.wechat_code = store.state.weChatCode;
    store.commit('setWeChatCode', '');
  }
  checkTCaptcha((ret) => {
    params.tcaptcha = ret;
    signUpAPI(params)
        .then(
            (res) => {
              Message.success(i18n.t('RegistrySuccess'));
              emits('loginRedirect', res.data.code);
            },
            (err) =>
              Modal.warning({
                title: i18n.t('RegistryFailed'),
                content: err.response.data.message,
                modalStyle: {textAlign: 'center'},
                width: 340,
                okText: i18n.t('OK'),
              }),
        )
        .finally(() => handleLoading(loading, false));
  });
};

// verify code
const defaultWaitTime = ref(60);
const waitTime = ref(0);
const checkWaitTime = () => {
  waitTime.value = waitTime.value - 1;
  if (waitTime.value <= 0) {
    waitTime.value = 0;
  } else {
    setTimeout(() => checkWaitTime(), 1000);
  }
};
const sendVerifyCode = () => {
  checkTCaptcha((ret) => {
    registryData.value.tcaptcha = ret;
    sendVerifyCodeAPI(registryData.value).then(
        () => {
          Message.success(i18n.t('VerifyCodeSendSuccess'));
          waitTime.value = defaultWaitTime.value;
          checkWaitTime();
        },
        (err) => Message.error(err.response.data.message),
    );
  });
};
</script>

<style scoped>
#registry-box {
  border-radius: var(--border-radius-medium);
  border: 1px solid var(--color-border-1);
  box-sizing: border-box;
  box-shadow: var(--shadow2-center);
  overflow: hidden;
}

#registry-box-title-box {
  background: linear-gradient(-45deg, rgb(var(--arcoblue-4)), rgb(var(--green-2)));
  padding: 32px 20px;
  margin-bottom: 20px;
}

#registry-box-title {
  text-align: center;
  margin: 0;
  color: var(--color-white);
}

.registry-box-form {
  width: 360px;
  padding: 20px;
  box-sizing: border-box;
}

.agreement-agree-box {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: -20px 0 20px 0;
  width: 100%;
  max-width: 360px;
  padding: 0 20px;
  box-sizing: border-box;
  word-break: break-all;
}

.agreement-agree-box :deep(.arco-space-item) > div > a {
  margin: 0;
  padding: 0;
  color: rgb(var(--arcoblue-6));
  cursor: pointer;
}
</style>
